### ISSUE TITLE
Implement mml gem for MathML parsing using lutaml-model

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/mml#1]
From:
* https://github.com/plurimath/plurimath/issues/302

**Comment by ronaldtse** [comment]
@suleman-uzair let's move the code from:
* https://github.com/plurimath/plurimath/pull/304

To this gem. Thanks!

We can use the namespace `Mml` or `Plurimath::Mml`

**Comment by ronaldtse** [comment]
We will need to add some round-tripping of MathML formulas, possibly just by copying them from Plurimath.

**Comment by ronaldtse** [comment]
The MathML 4.0 schema source is actually from RNC:

* https://github.com/w3c/mathml-schema/tree/main/rnc

But you can use the generated XSD files to generate the models:

* https://github.com/w3c/mathml-schema/tree/main/xsd

**Comment by suleman-uzair** [comment]
@ronaldtse **MathML4** schema seems incomplete to me, as mentioned in their **[README.md](https://github.com/w3c/mathml-schema?tab=readme-ov-file#mathml-schema)** file.
> Generated Schema for MathML4 drafts

I did try to generate the files/classes using **Shale** for **MathML4**, but it only generated a few classes.
I will continue with the **MathML3** schema for now as it seems to be complete.

**Comment by ronaldtse** [comment]
@suleman-uzair please also try to add round-trip specs for the library. Have a look at what is done in the ogc-gml gem and the rfcxml gems. You can copy and paste that structure in to ensure the parser is faithful.

**Comment by suleman-uzair** [comment]
> Have a look at what is done in the ogc-gml gem and the rfcxml gems.

@ronaldtse, Sure, I’ll look into it after finalizing the **Plurimath#to_mathml** conversion.
